# AlaraMono Nerd Font", style = "Regular" }critty Configuration File
[window]
dimensions = { columns = 180, lines = 50 }
startup_mode = "Windowed"
position = { x = 0, y = 0 }
padding = { x = 0, y = 0 }
decorations = "full"
title = "Alacritty"
opacity = 1

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "FiraMono Nerd Font", style = "Regular" }
bold = { family = "FiraMono Nerd Font", style = "Bold" }
italic = { family = "FiraMono Nerd Font", style = "Italic" }
size = 10.5
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[colors]
[colors.primary]
background = "0x101010"
foreground = "0xebdbb2"

[colors.normal]
black = "0x101010"
red = "0xcc241d"
green = "0x98971a"
yellow = "0xd79921"
blue = "0x458588"
magenta = "0xb16286"
cyan = "0x689d6a"
white = "0xa89984"

[colors.bright]
black = "0x928374"
red = "0xfb4934"
green = "0xb8bb26"
yellow = "0xfabd2f"
blue = "0x83a598"
magenta = "0xd3869b"
cyan = "0x8ec07c"
white = "0xebdbb2"

[cursor]
style = "Block"

[terminal]
shell = { program = "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", args = ["-NoLogo"] }
